### ISSUE TITLE
implmenting hdl-util/hdmi on a Spartan Edge Accelerator system

### ISSUE THREAD

**Issue by n3rdx** [hdl-util/hdmi#32]
Hi, @sameer I have Spartan Edge Accelerator, and have a project in progress that would be able to use it (a high quality, live stream showcasing free discussions between senior hardware engineers discussing tips/procedures for EE/RF/Aerospace) where I could possibly output some translated waveforms - and I have a complex professional/prosumer OBS Studio setup. I sent you Linked In invite and would like to know if there is a writeup on the process by which you adapted Spartan Edge Accelerator with HDMI interface where I can add in my contributions, 

Ref: [Hackster.io article ](https://www.hackster.io/shengr/xilinx-vivado-board-files-for-spartan-edge-accelerator-1-e99826)

**Comment by sameer** [comment]
Responded on LinkedIn, you can look at https://github.com/hdl-util/hdmi-demo which has an example implementation for the SEA board
